import type { Metadata, Viewport } from 'next'
import type { ReactNode } from 'react'
import Script from 'next/script'
import { Bebas_Neue, Inter } from 'next/font/google'
import { TOTAL_FIGURES_LABEL } from '@/data/kb-stats'
import Footer from './components/Footer'
import './globals.css'

// Self-hosted via next/font (S20 perf audit): the old render-blocking
// fonts.googleapis.com stylesheet cost 100-300ms FCP on every cold visit and
// pulled font files from a second origin. next/font serves woff2 from
// /_next/static (same origin, immutable cache) with size-adjusted fallback
// metrics, so there is no render-blocking CSS and no font layout shift.
// globals.css resolves --font-display/--font-ui through these variables.
const bebas = Bebas_Neue({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-bebas',
  display: 'swap',
})
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

export const metadata: Metadata = {
  title: {
    default: 'FigurePinner — Action Figure Price Intelligence',
    template: '%s | FigurePinner',
  },
  description:
    `The action figure collector's edge. Real sold prices, series completion tracking, and deal alerts — for ${TOTAL_FIGURES_LABEL} figures.`,
  keywords: [
    'action figure prices',
    'WWE figure prices',
    'wrestling figure values',
    'action figure collection tracker',
    'eBay sold prices',
    'figure price guide',
  ],
  authors: [{ name: 'FigurePinner' }],
  creator: 'FigurePinner',
  metadataBase: new URL('https://figurepinner.com'),
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://figurepinner.com',
    siteName: 'FigurePinner',
    title: 'FigurePinner — Action Figure Price Intelligence',
    description:
      'Real sold prices, series completion tracking, and deal alerts for action figure collectors.',
    // OG image auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'FigurePinner — Action Figure Price Intelligence',
    description: `Real sold prices for ${TOTAL_FIGURES_LABEL} action figures across 16 genres.`,
    // Twitter card image auto-pulled from opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
    },
  },
  icons: {
    icon: '/favicon.svg',
    shortcut: '/favicon.svg',
    // apple-touch-icon: add a 180×180 PNG to public/ once brand assets are ready
  },
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: '#09090F',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning className={`${bebas.variable} ${inter.variable}`}>
      <head>
        {/* AdSense ownership verification — the meta tag is what the reviewer
            checks; it stays in head while the script loads lazily below. */}
        <meta name="google-adsense-account" content="ca-pub-1062337951127266" />
      </head>
      <body>
        {children}
        <Footer />
        {/* Google AdSense — auto ads. lazyOnload (S20 perf audit): the script
            used to load render-blocking-adjacent in <head>, competing for
            bandwidth/CPU in the critical first-load window on every page.
            Ads here are below-fold reading-flow units; nothing above the fold
            depends on them, and ~99% of traffic is bots that earn nothing. */}
        <Script
          id="adsbygoogle-loader"
          strategy="lazyOnload"
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1062337951127266"
          crossOrigin="anonymous"
        />
      </body>
    </html>
  )
}
