import type { Metadata, Viewport } from 'next'
import type { ReactNode } from 'react'
import { Bebas_Neue, Inter, Cinzel } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { TOTAL_FIGURES_LABEL } from '@/data/kb-stats'
import Footer from './components/Footer'
import FunnelTracker from './_components/FunnelTracker'
import CfBeacon from './_components/CfBeacon'
// Claiming Ritual — Session 1 de-risk gate spike (bare photo-flight only, no
// nameplate/particles/sound). Client-only: it reads window/document geometry
// (getBoundingClientRect, matchMedia, startViewTransition) that doesn't exist
// during SSR. layout.tsx is a Server Component, and Next forbids a
// next/dynamic({ ssr:false }) call directly inside one, so the dynamic()
// call itself lives in ClaimRitualLoader.tsx (a 'use client' file) — this
// import just gets the already-wrapped component. Mounted once, globally,
// exactly like FunnelTracker below. See src/app/components/ClaimRitual.tsx.
import ClaimRitual from './components/ClaimRitualLoader'
import './globals.css'

// Self-hosted via next/font (S20 perf audit): the old render-blocking
// fonts.googleapis.com stylesheet cost 100-300ms FCP on every cold visit and
// pulled font files from a second origin. next/font serves woff2 from
// /_next/static (same origin, immutable cache) with size-adjusted fallback
// metrics, so there is no render-blocking CSS and no font layout shift.
// globals.css resolves --font-display/--font-ui through these variables.
const bebas = Bebas_Neue({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-bebas',
  display: 'swap',
})
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})
// Cinzel (SIL OFL, Google Fonts) — heroic-poster serif for the MOTU fandom hub
// ONLY. preload:false so the woff2 is fetched only on pages that actually render
// [data-fandom="masters-of-the-universe"] type — zero added weight sitewide (CWV
// guardrail). display:swap + serif fallback keeps the hero title paintable at FCP.
const cinzel = Cinzel({
  weight: ['400', '700', '900'],
  subsets: ['latin'],
  variable: '--font-cinzel',
  display: 'swap',
  preload: false,
  adjustFontFallback: true, // size-adjusted serif fallback → no CLS on the swap
})

export const metadata: Metadata = {
  title: {
    default: 'FigurePinner — Action Figure Price Intelligence',
    template: '%s | FigurePinner',
  },
  description:
    `The action figure collector's edge. Real sold prices, series completion tracking, and deal alerts — for ${TOTAL_FIGURES_LABEL} figures.`,
  keywords: [
    'action figure prices',
    'WWE figure prices',
    'wrestling figure values',
    'action figure collection tracker',
    'eBay sold prices',
    'figure price guide',
  ],
  authors: [{ name: 'FigurePinner' }],
  creator: 'FigurePinner',
  metadataBase: new URL('https://figurepinner.com'),
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://figurepinner.com',
    siteName: 'FigurePinner',
    title: 'FigurePinner — Action Figure Price Intelligence',
    description:
      'Real sold prices, series completion tracking, and deal alerts for action figure collectors.',
    // OG image auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'FigurePinner — Action Figure Price Intelligence',
    description: `Real sold prices for ${TOTAL_FIGURES_LABEL} action figures across 16 genres.`,
    // Twitter card image auto-pulled from opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
    },
  },
  icons: {
    icon: '/favicon.svg',
    shortcut: '/favicon.svg',
    // apple-touch-icon: add a 180×180 PNG to public/ once brand assets are ready
  },
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: '#09090F',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning className={`${bebas.variable} ${inter.variable} ${cinzel.variable}`}>
      <head>
        {/* AdSense ownership verification — the meta tag is what the reviewer
            checks; it stays in head while the script loads lazily below. */}
        <meta name="google-adsense-account" content="ca-pub-1062337951127266" />
        <meta name="yandex-verification" content="5dd6adeb78ca7373" />
        {/* Build stamp — which BUILD rendered this page (ISR pages cache HTML
            across deploys, so this can lag the deployed sha; that lag is the
            signal). Compare against /api/version. See next.config.ts. */}
        <meta name="fp-build" content={process.env.FP_BUILD_SHA ?? 'unknown'} />
      </head>
      <body>
        {/* Plain ClerkProvider, NO `dynamic` prop (S70 fix, 2026-07-07, per
            standalone's spec: STANDALONE-TO-WEB-CLERK-HEADER-FIX-SPEC).
            `dynamic` opts a subtree into per-request rendering, which needs
            clerkMiddleware() to have processed the request — that's what
            broke the first attempt, since middleware.ts's matcher
            deliberately excludes public routes (S19, bot-traffic cost).
            Plain ClerkProvider on v6 does NOT force dynamic rendering, so
            public pages stay static/ISR'd exactly as before; SiteHeader's
            <SignedIn>/<SignedOut> read Clerk's CLIENT-side session state
            after hydration instead, no middleware coverage required.
            app/app/layout.tsx keeps its own <ClerkProvider dynamic> for real
            per-request auth() calls in /app — unchanged, untouched. */}
        <ClerkProvider>
          <FunnelTracker />
          <ClaimRitual />
          {children}
          <Footer />
        </ClerkProvider>
        {/* AD STANDARD v2 (2026-07-19): AdSense auto-ads script removed —
            unconditional sitewide loader wrapping every route incl. signed-in
            surfaces, Google-chosen placements, no unit ever rendered (the
            <ins> branch in AdSlot.tsx was always commented out). Adsterra
            iframe banners only, per-page-type, per the format ruling. */}
        {/* Adsterra Popunder — DISABLED. Was intercepting internal nav clicks
            and serving adult inventory. Use Native Banner only. */}
        {/* <Script
          id="adsterra-popunder"
          strategy="lazyOnload"
          src="https://pl29755501.effectivecpmnetwork.com/57/09/40/57094087da8eb25d6b0930dc2e36c3a1.js"
        /> */}
        {/* Infolinks — REMOVED. Declined due to 404 error on their review. */}
        {/* Cloudflare Web Analytics beacon - bot-filtered real human visit count.
            QA-exclusion (2026-07-17): wrapped in a client component so a flagged
            team-QA browser (localStorage fp_qa, see qaFlag.ts) sends zero RUM
            pageviews -- team verification browsing was contaminating the real
            R1 visitor count. */}
        <CfBeacon />
      </body>
    </html>
  )
}
