import type { Metadata, Viewport } from 'next'
import type { ReactNode } from 'react'
import { ClerkProvider } from '@clerk/nextjs'
import { TOTAL_FIGURES_LABEL } from '@/data/kb-stats'
import Footer from './components/Footer'
import './globals.css'

export const metadata: Metadata = {
  title: {
    default: 'FigurePinner — Action Figure Price Intelligence',
    template: '%s | FigurePinner',
  },
  description:
    `The action figure collector's edge. Real sold prices, series completion tracking, and deal alerts — for ${TOTAL_FIGURES_LABEL} figures.`,
  keywords: [
    'action figure prices',
    'WWE figure prices',
    'wrestling figure values',
    'action figure collection tracker',
    'eBay sold prices',
    'figure price guide',
  ],
  authors: [{ name: 'FigurePinner' }],
  creator: 'FigurePinner',
  metadataBase: new URL('https://figurepinner.com'),
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://figurepinner.com',
    siteName: 'FigurePinner',
    title: 'FigurePinner — Action Figure Price Intelligence',
    description:
      'Real sold prices, series completion tracking, and deal alerts for action figure collectors.',
    // OG image auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'FigurePinner — Action Figure Price Intelligence',
    description: `Real sold prices for ${TOTAL_FIGURES_LABEL} action figures across 16 genres.`,
    // Twitter card image auto-pulled from opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
    },
  },
  icons: {
    icon: '/favicon.svg',
    shortcut: '/favicon.svg',
    // apple-touch-icon: add a 180×180 PNG to public/ once brand assets are ready
  },
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: '#09090F',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <ClerkProvider dynamic>
      <html lang="en" suppressHydrationWarning>
        <head>
          {/* Google Fonts — preconnect first for perf */}
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
          <link
            href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:wght@300;400;500;600;700;800&display=swap"
            rel="stylesheet"
          />
        </head>
        <body>
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  )
}
