// Bid Check guides — figure-value + "most valuable [line]" pages (Front 2 spearhead,
// Traffic Week 2026-06-25). Same Article shape + collector voice as articles.ts; the
// difference is the `comp` blocks, which render LIVE r2proxy sold-medians (the moat:
// a competitor can copy prose, not a live median). Numbers in prose are the reading
// at publish; the comp cards are the always-current truth and self-update hourly.
//
// Data sourced 2026-06-25 from r2proxy price-summaries via scripts/bidcheck-pull.cjs.
// fids are stable; comp "see every sold" links point at /figure/<fid> (always resolves).

import type { Article } from './articles'

export const BIDCHECK_ARTICLES: Article[] = [
  // ───────────────────────── MOST-VALUABLE LISTS ─────────────────────────
  {
    slug: 'most-valuable-star-wars-black-series',
    title: 'The Most Valuable Star Wars Black Series Figures',
    metaTitle: 'Most Valuable Star Wars Black Series Figures — Real Sold Prices | FigurePinner',
    metaDescription:
      'The Star Wars Black Series pieces that actually hold money — real eBay sold medians on the SDCC exclusives, 6-inch two-packs, deluxe sets, and the playsets and Force FX sabers that top the whole line.',
    dek: 'Most of the line is $15 to $30. A short list of exclusives, two-packs, and big-ticket items is where the real money sits, and the sold data shows exactly where.',
    readingMinutes: 6,
    updated: '2026-06-25',
    body: [
      { type: 'p', text: 'The Black Series is the deepest modern Star Wars line, and most of it is genuinely cheap. The standard carded figure most collectors own trades in the $15 to $30 range and stays there, because Hasbro prints the mainline deep. The money is somewhere else: the exclusives, the deluxe sets, and the handful of vehicles and props Hasbro priced as premium items from the start. Real sold comps draw the line.' },
      { type: 'h2', text: 'The items that top the entire line' },
      { type: 'p', text: 'Before the figures, the most valuable things wearing the Black Series banner are not figures at all. They are the big-ticket playsets and the Force FX sabers, and they sit well above everything else.' },
      { type: 'comp', fid: 'fp_star-wars_hasbro_black-series_3-75-playsets_jabbas-rancor-pit_08a79d', label: "Jabba's Rancor Pit", sublabel: 'Black Series playset', href: '/figure/fp_star-wars_hasbro_black-series_3-75-playsets_jabbas-rancor-pit_08a79d' },
      { type: 'comp', fid: 'fp_star-wars_hasbro_black-series_exclusives_reva-force-fx-elite-lightsaber_098501', label: 'Reva Force FX Elite Lightsaber', sublabel: '6-inch Black Series exclusive', href: '/figure/fp_star-wars_hasbro_black-series_exclusives_reva-force-fx-elite-lightsaber_098501' },
      { type: 'h2', text: 'The figures that actually hold value' },
      { type: 'p', text: 'Among the figures themselves, the pattern is consistent: two-packs, deluxe sets with a vehicle or a beast, and convention exclusives. These are the releases capped at a number, and a capped print run is the one thing the mainline cannot reprint into the floor.' },
      { type: 'comp', fid: 'fp_star-wars_hasbro_black-series_galaxy_yoda-clone-commander-gree_660e26', label: 'Yoda & Clone Commander Gree', sublabel: '6-inch two-pack', href: '/figure/fp_star-wars_hasbro_black-series_galaxy_yoda-clone-commander-gree_660e26' },
      { type: 'comp', fid: 'fp_star-wars_hasbro_black-series_deluxe-sets_sandtrooper-and-dewback_618522', label: 'Sandtrooper and Dewback', sublabel: '6-inch deluxe set', href: '/figure/fp_star-wars_hasbro_black-series_deluxe-sets_sandtrooper-and-dewback_618522' },
      { type: 'comp', fid: 'fp_star-wars_hasbro_black-series_exclusives_grand-admiral-thrawn_6baede', label: 'Grand Admiral Thrawn', sublabel: '6-inch SDCC exclusive', href: '/figure/fp_star-wars_hasbro_black-series_exclusives_grand-admiral-thrawn_6baede' },
      { type: 'comp', fid: 'fp_star-wars_hasbro_black-series_exclusives_heroes-of-endor_051a9c', label: 'Heroes of Endor', sublabel: '6-inch multipack', href: '/figure/fp_star-wars_hasbro_black-series_exclusives_heroes-of-endor_051a9c' },
      { type: 'callout', text: 'Watch the sample sizes on the live cards. The Yoda two-pack and the Thrawn SDCC both clear on 30-plus sold, which is a liquid market you can trust within a few dollars. A figure with a handful of sales is where the price gets noisy.' },
      { type: 'h2', text: 'Why these and not the rest' },
      { type: 'p', text: 'The value driver is the release, not the character. A standard single Vader or Luke is $15 to $25 no matter how iconic the name, because Hasbro made an ocean of them. It is the SDCC and convention pieces, the deluxe sets, and the two-packs that finish a scene that escape the common floor. When you price a Black Series figure, price the exact release and its sample size, not the character on the card.' },
      { type: 'p', text: 'Browsing a different line? [[Start from sold comps, not asking prices|/guides/how-to-find-action-figure-values]] — it is the habit that separates a real value from a hopeful listing.' },
    ],
  },
  {
    slug: 'most-valuable-aew-figures',
    title: 'The Most Valuable AEW Figures',
    metaTitle: 'Most Valuable AEW Figures — Real Sold Prices (Jazwares Unrivaled) | FigurePinner',
    metaDescription:
      'What the priciest AEW figures actually sell for — Jazwares Unrivaled exclusives, the Death Triangle and Lucha Bros tag packs, Supreme chase figures, and why a line this young already has $100-plus pieces.',
    dek: "Jazwares' AEW line is barely five years old, so the value is not vintage — it is exclusives, tag packs, and the Lucha Bros. The sold data shows where.",
    readingMinutes: 5,
    updated: '2026-06-25',
    body: [
      { type: 'p', text: 'AEW figures are a young market. The Jazwares Unrivaled line started in 2020, so there is no vintage premium to lean on the way there is with WWF Hasbro or LJN. The value comes from one place instead: scarcity built in at release, through retailer exclusives, short-printed tag packs, and the Supreme chase figures.' },
      { type: 'h2', text: 'The exclusives and tag packs that top the line' },
      { type: 'p', text: 'The most valuable AEW pieces are the retailer-exclusive multipacks, and the Lucha Bros sit at the center of nearly all of them.' },
      { type: 'comp', fid: 'fp_wrestling_jazwares_aew-unrivaled_ex_death-triangle-3_9bff47', label: 'Death Triangle 3-Pack (PAC, Fenix, Penta)', sublabel: 'AEW Unrivaled exclusive', href: '/figure/fp_wrestling_jazwares_aew-unrivaled_ex_death-triangle-3_9bff47' },
      { type: 'comp', fid: 'fp_wrestling_jazwares_aew-unrivaled_ex_amazon-exclusive_8eb1a0', label: 'Rey Fenix & Penta — Amazon Tag Pack', sublabel: 'AEW Unrivaled exclusive', href: '/figure/fp_wrestling_jazwares_aew-unrivaled_ex_amazon-exclusive_8eb1a0' },
      { type: 'comp', fid: 'fp_wrestling_jazwares_aew-unrivaled_ex_shop-aew-exclusi_2fa0e7', label: 'Shop AEW Exclusive Kazuchika Okada', sublabel: 'AEW Unrivaled exclusive', href: '/figure/fp_wrestling_jazwares_aew-unrivaled_ex_shop-aew-exclusi_2fa0e7' },
      { type: 'callout', text: 'The Lucha Bros, Rey Fenix and Penta, are the names to track. They appear in the priciest packs again and again, and a Fenix or Penta exclusive has been a reliable hold since the line began.' },
      { type: 'h2', text: 'The Supreme chase tier' },
      { type: 'p', text: 'Above the standard Unrivaled releases sits the Supreme Collection, the premium short-run tier. These were capped tighter than the mainline and command it.' },
      { type: 'comp', fid: 'fp_wrestling_jazwares_aew-supreme_3_rey-fenix_6cd344', label: 'Rey Fenix — AEW Supreme', sublabel: 'Supreme Collection chase', href: '/figure/fp_wrestling_jazwares_aew-supreme_3_rey-fenix_6cd344' },
      { type: 'h2', text: 'What this means if you collect AEW' },
      { type: 'p', text: 'Chase the exclusives and the packs, not the mainline singles. A standard Unrivaled single is $10 to $20 and stays there, because Jazwares prints them deep and the line is still in production. The money is in the retailer-exclusive tag packs and the Supreme chases, which were capped at release and cannot be flooded back onto the market.' },
      { type: 'p', text: 'New to reading a market this young? [[Learn how to find what a figure is really worth|/guides/how-to-find-action-figure-values]] before you pay an exclusive premium.' },
    ],
  },
  {
    slug: 'most-valuable-gi-joe-classified-figures',
    title: 'The Most Valuable G.I. Joe Classified Figures',
    metaTitle: 'Most Valuable G.I. Joe Classified Series Figures — Real Sold Prices | FigurePinner',
    metaDescription:
      'The G.I. Joe Classified Series pieces that actually hold money — the vehicles that out-price every figure, the Cobra troop-builders, and the short-printed exclusives. Real eBay sold comps.',
    dek: 'The twist with Classified: the most valuable items are not figures, they are the vehicles. But a handful of single figures carry real money too.',
    readingMinutes: 5,
    updated: '2026-06-25',
    body: [
      { type: 'p', text: 'G.I. Joe Classified is Hasbro’s modern 6-inch line, and the value story has a clear shape. The very top is dominated by vehicles and crowdfunded pieces, not figures at all. The single-figure money lives a tier down, in Cobra troop-builders and a few short-printed exclusives.' },
      { type: 'h2', text: 'The vehicles are the grails' },
      { type: 'p', text: 'By a wide margin, the most valuable Classified items are the large vehicles. They were expensive at retail, produced in smaller numbers, and they clear on deep sample counts.' },
      { type: 'comp', fid: 'fp_gi-joe_hasbro_classified-series_classified_cobra-rattler-ground-attack-jet_ca72be', label: 'Cobra Rattler Ground Attack Jet', sublabel: 'Classified vehicle', href: '/figure/fp_gi-joe_hasbro_classified-series_classified_cobra-rattler-ground-attack-jet_ca72be' },
      { type: 'comp', fid: 'fp_gi-joe_hasbro_classified-series_classified_cobra-h-i-s-s-tank_d4f0bd', label: 'Cobra H.I.S.S. Tank', sublabel: 'Classified vehicle', href: '/figure/fp_gi-joe_hasbro_classified-series_classified_cobra-h-i-s-s-tank_d4f0bd' },
      { type: 'comp', fid: 'fp_gi-joe_hasbro_classified-series_classified_clutch-with-vamp_28c6f7', label: 'Clutch with VAMP', sublabel: 'Classified figure + vehicle', href: '/figure/fp_gi-joe_hasbro_classified-series_classified_clutch-with-vamp_28c6f7' },
      { type: 'callout', text: 'These clear between $250 and $435, and the sample sizes are deep — the H.I.S.S. Tank on roughly 49 sold, the Rattler on 19. When a big-ticket item has a sample that deep, the median is the real number, not a lucky auction.' },
      { type: 'h2', text: 'The single figures that hold value' },
      { type: 'p', text: 'Among figures alone, the money is in army-builders and short-printed exclusives. A Cobra trooper gets bought in multiples to fill a shelf, and structural demand like that holds a price the way a single hero figure never does.' },
      { type: 'comp', fid: 'fp_gi-joe_hasbro_classified-series_classified_cobra-wild-weasel_f98a00', label: 'Cobra Wild Weasel', sublabel: 'Classified figure', href: '/figure/fp_gi-joe_hasbro_classified-series_classified_cobra-wild-weasel_f98a00' },
      { type: 'comp', fid: 'fp_gi-joe_hasbro_classified-series_classified_cobra-s-n-a-k-e-system-neutralizer-armed-kloaking-equipment-battle-suit_fdec64', label: 'Cobra S.N.A.K.E. Battle Suit', sublabel: 'Classified army-builder', href: '/figure/fp_gi-joe_hasbro_classified-series_classified_cobra-s-n-a-k-e-system-neutralizer-armed-kloaking-equipment-battle-suit_fdec64' },
      { type: 'h2', text: 'What drives Classified value' },
      { type: 'p', text: 'Two forces: capped supply and builder demand. The vehicles and crowdfunded pieces were produced to a number and never reprinted, while the troop-builders get bought in quantity. The standard mainline retail figure, by contrast, stays in the $20 to $30 range, because Hasbro keeps it on shelves. Price the exact release, and check whether you are looking at a capped item or an evergreen one.' },
      { type: 'p', text: 'Pricing something outside Joe? [[The same sold-comp method works on any line|/guides/how-to-find-action-figure-values]].' },
    ],
  },

  // ───────────────────────── FIGURE-VALUE GUIDES ─────────────────────────
  {
    slug: 'hulk-hogan-figure-value',
    title: 'Hulk Hogan Figures: What the Biggest Name in Wrestling Actually Sells For',
    metaTitle: 'Hulk Hogan Figure Value — Real Sold Prices, Vintage to Modern | FigurePinner',
    metaDescription:
      'What Hulk Hogan action figures really sell for — from $2 modern Elites to the $100-plus LJN vintage and the Stretch Wrestler grail. Real eBay sold comps, and why the most-printed wrestler still hides a few.',
    dek: 'The most famous name in wrestling, and most of his figures cost less than lunch. Then there is the vintage LJN. The sold data tells both stories.',
    readingMinutes: 6,
    updated: '2026-06-25',
    body: [
      { type: 'p', text: 'Nobody in wrestling got more action figures than Hulk Hogan. He headlined for forty years across the WWF, WCW, and back again, and every company that held his license printed him hard. The result shows up clearly in the sold data: dozens of distinct Hogan figures, a floor under two dollars, and a ceiling north of two hundred. That spread is the entire lesson.' },
      { type: 'h2', text: 'The vintage LJN is the grail' },
      { type: 'p', text: 'If a Hogan figure carries real money, it is almost always an early LJN release. LJN came from a smaller, earlier era of production, and those figures never got the endless modern reprints.' },
      { type: 'comp', fid: 'fp_wrestling_ljn_ljn-wwf_ex_series-16-articu_759abd', label: 'LJN WWF 16-inch Articulated Hogan', sublabel: 'vintage LJN', href: '/figure/fp_wrestling_ljn_ljn-wwf_ex_series-16-articu_759abd' },
      { type: 'comp', fid: 'fp_wrestling_ljn_ljn-wwf_ex_stretch-wrestler_3357c4', label: 'LJN Stretch Wrestlers Hogan', sublabel: 'vintage LJN', href: '/figure/fp_wrestling_ljn_ljn-wwf_ex_stretch-wrestler_3357c4' },
      { type: 'callout', text: 'The 16-inch clears its median on a deep sample, so trust that number. The Stretch Wrestler clears higher but on far fewer sales, so read its price as a soft ceiling that a single motivated bidder can move either way.' },
      { type: 'h2', text: 'The mid-tier: WCW and the two-packs' },
      { type: 'p', text: 'Between the vintage grails and the cheap modern floor sit the WCW Toy Biz nWo multipacks and the Jakks Classic Superstars two-packs. The two-packs in particular ride a second name; a Hogan-versus-Andre set is buying a piece of history, not just a figure.' },
      { type: 'comp', fid: 'fp_wrestling_jakks-pacific_classic-superstars_ex_hulk-hogan-vs-an_d610a5', label: 'Hulk Hogan vs. Andre the Giant', sublabel: 'Jakks Classic Superstars two-pack', href: '/figure/fp_wrestling_jakks-pacific_classic-superstars_ex_hulk-hogan-vs-an_d610a5' },
      { type: 'h2', text: 'Why the modern Hogan stays cheap' },
      { type: 'p', text: 'The same rule that catches new collectors applies to Hogan in full. Mattel printed him in Elite, Ultimate Edition, and Retro, over and over, and supply on that scale never becomes scarce. Fame drives print runs; scarcity drives price; and a name as big as Hogan guaranteed he would always be easy to find. A loose modern Hogan can cost a couple of dollars, and that is exactly what the data predicts.' },
      { type: 'p', text: 'Before you buy or sell one, pull the real history. [[Look up any Hulk Hogan figure|/wrestling/character/hulk-hogan]] for the median, the range, and the sale count behind it. For the wider how-to, [[start with sold comps, not listings|/guides/how-to-find-action-figure-values]].' },
    ],
  },
  {
    slug: 'undertaker-figure-value',
    title: 'Undertaker Figures: From $7 Shelf-Fillers to a $200 Hasbro Grail',
    metaTitle: 'Undertaker Figure Value — Real Sold Prices, Hasbro to Elite | FigurePinner',
    metaDescription:
      'What Undertaker action figures sell for — the modern Elites under $20, and the vintage WWF Hasbro that clears $200 across dozens of sales. Real eBay sold comps and where the Deadman’s value hides.',
    dek: 'More than a hundred Undertaker figures, priced from seven dollars to two-fifty. The vintage Hasbro is the one that matters.',
    readingMinutes: 5,
    updated: '2026-06-25',
    body: [
      { type: 'p', text: 'The Undertaker has been an action figure in nearly every wrestling line for more than thirty years, which means the data on him is deep and the spread is enormous. More than a hundred distinct Undertaker figures carry sold comps. Most are cheap. One is a genuine grail, and it has the sales to prove it is not a fluke.' },
      { type: 'h2', text: 'The vintage WWF Hasbro is the grail' },
      { type: 'comp', fid: 'fp_wrestling_hasbro_wwf-hasbro_8_undertaker_c60ced', label: 'Undertaker — WWF Hasbro', sublabel: 'vintage Hasbro', href: '/figure/fp_wrestling_hasbro_wwf-hasbro_8_undertaker_c60ced' },
      { type: 'p', text: 'The Hasbro Undertaker clears its median across roughly thirty sold, and that sample size is what makes it real. This is not one lucky auction; it is a deep, liquid market agreeing that the figure is worth around two hundred dollars. It was a late-run Hasbro release, produced in smaller numbers than the early series, and late-run Hasbro is where the vintage WWF money consistently lives.' },
      { type: 'callout', text: 'A median backed by thirty-plus sales is about as trustworthy as a vintage comp gets. When you see a sample that deep, the price is the price, and you can buy or sell with confidence.' },
      { type: 'h2', text: 'The Jakks two-packs are the mid-tier' },
      { type: 'p', text: 'Between the vintage grail and the cheap modern floor sit the Jakks Deluxe Classic two-packs, which pair the Deadman with his storyline partners.' },
      { type: 'comp', fid: 'fp_wrestling_jakks-pacific_deluxe-classic_ex_brothers-of-dest_324a85', label: 'Brothers of Destruction: Kane & Undertaker', sublabel: 'Jakks Deluxe Classic two-pack', href: '/figure/fp_wrestling_jakks-pacific_deluxe-classic_ex_brothers-of-dest_324a85' },
      { type: 'h2', text: 'Why the modern Undertaker is cheap' },
      { type: 'p', text: 'Mattel has printed the Deadman in Elite after Elite, plus Ultimate Edition and Retro, for over a decade. A collector who simply wants an Undertaker on the shelf has dozens of inexpensive options, so the floor sits near seven dollars. Only the vintage and the short-printed sets escape it. Fame guaranteed the print runs; the print runs guaranteed the low price.' },
      { type: 'p', text: 'Check the real number before you pay. [[Look up any Undertaker figure|/wrestling/character/undertaker]] for the median, range, and sale count. New to comps? [[Here is how to find what a figure is worth|/guides/how-to-find-action-figure-values]].' },
    ],
  },
  {
    slug: 'stone-cold-steve-austin-figure-value',
    title: 'Stone Cold Steve Austin Figures: The Biggest Draw, the Smallest Premiums',
    metaTitle: 'Stone Cold Steve Austin Figure Value — Real Sold Prices | FigurePinner',
    metaDescription:
      'What Stone Cold Steve Austin figures actually sell for — the biggest draw of the Attitude Era, yet nothing across dozens of figures breaks $50. Real eBay sold comps and the honest reason volume beats fame.',
    dek: 'He sold more merchandise than anyone in wrestling history. None of his figures crack fifty dollars. That is not a contradiction, it is the whole point.',
    readingMinutes: 5,
    updated: '2026-06-25',
    body: [
      { type: 'p', text: 'Stone Cold Steve Austin was the biggest draw the business has ever produced, the engine of the Attitude Era boom. His figures are some of the easiest in the hobby to price, because there is no grail to hunt. Across dozens of Austin figures with real sold comps, the ceiling sits around forty dollars.' },
      { type: 'p', text: 'For a wrestler of his stature, that is remarkable, and it is the clearest proof of a rule new collectors learn the hard way: fame and figure value are not the same thing, and they are frequently inverse.' },
      { type: 'h2', text: 'The ceiling is the mid-tier' },
      { type: 'comp', fid: 'fp_wrestling_mattel_defining-moments_6_steve-austin_626ed8', label: 'Steve Austin — Defining Moments', sublabel: 'Mattel', href: '/figure/fp_wrestling_mattel_defining-moments_6_steve-austin_626ed8' },
      { type: 'comp', fid: 'fp_wrestling_mattel_ultimate-edition_9_stone-cold-steve_41cafb', label: 'Stone Cold Steve Austin — Ultimate Edition', sublabel: 'Mattel', href: '/figure/fp_wrestling_mattel_ultimate-edition_9_stone-cold-steve_41cafb' },
      { type: 'callout', text: 'Look at the sample sizes on the cards above. The top Austin figures clear on around fifty sold each. These are not thin markets where the price is uncertain; the market is deep and the price is still low, which only happens when supply is enormous.' },
      { type: 'h2', text: 'Why the biggest star has the smallest premiums' },
      { type: 'p', text: 'Austin’s peak lined up with the biggest boom wrestling has ever had. Everyone who wanted Austin product got it, the companies kept printing because it kept selling, and twenty-five years later that supply is still on the market. He was made too much, too well, for too long to ever become scarce.' },
      { type: 'p', text: 'The lesson generalizes to the whole hobby. A wrestler being your favorite, or the greatest of all time, tells you nothing about what his figure is worth. Supply does. Austin is the cleanest example of it on the shelf.' },
      { type: 'h2', text: 'Where an Austin figure could still carry money' },
      { type: 'p', text: 'If any Austin escapes the forty-dollar ceiling, it will be a condition story rather than a release: a sharp, sealed vintage card graded into the preservation market, or a genuinely short-printed exclusive. For the everyday loose Austin, the honest answer is that it is a common figure, and that is fine. You collect Austin because Austin meant something, not because the plastic is an investment.' },
      { type: 'p', text: 'Confirm any Austin before you buy or sell. [[Look up every Steve Austin figure|/wrestling/character/steve-austin]] for the real median and sale count, and [[learn to read sold comps|/guides/how-to-find-action-figure-values]] so fame never sets your price.' },
    ],
  },
  {
    slug: 'darth-vader-figure-value',
    title: 'Darth Vader Figures: Why They Run From $4 to $850',
    metaTitle: 'Darth Vader Figure Value — Real Sold Prices, Black Series to Hot Toys | FigurePinner',
    metaDescription:
      'What Darth Vader figures sell for across the range — $15 Black Series singles up to $850 Hot Toys. Real eBay sold comps and what actually separates a cheap Vader from a four-figure one.',
    dek: 'The most-figured villain in the hobby spans an enormous price range. Scale and maker explain almost all of it.',
    readingMinutes: 6,
    updated: '2026-06-25',
    body: [
      { type: 'p', text: 'Darth Vader is the most-figured villain in collecting, and the price range is staggering: well over a hundred Vader figures carry sold comps, from about four dollars to eight hundred and fifty. Understanding that spread is really understanding how the entire Star Wars market is tiered, because the same character sits in every tier at once.' },
      { type: 'h2', text: 'The Black Series tier: $15 to $40' },
      { type: 'p', text: 'The 6-inch Black Series is where most collectors meet Vader, and it behaves like every mass-retail line: deep supply, modest prices. A standard carded Vader runs in the teens to twenties; the better-sculpted Galaxy and deluxe versions reach the forties.' },
      { type: 'comp', fid: 'fp_star-wars_hasbro_black-series_galaxy_darth-vader_47b867', label: 'Darth Vader (A New Hope) — 6-inch Black Series', sublabel: 'Hasbro', href: '/figure/fp_star-wars_hasbro_black-series_galaxy_darth-vader_47b867' },
      { type: 'h2', text: 'The Hot Toys tier: $300 and up' },
      { type: 'p', text: 'At the top is Hot Toys’ sixth-scale line, a different product for a different buyer. These start around three to four hundred dollars at retail, and the discontinued ones climb from there. The Tarkin two-pack is the current ceiling.' },
      { type: 'comp', fid: 'fp_star-wars_hot-toys_hot-toys_action-figures_grand-moff-tarkin-and-darth-vade_5f77da', label: 'Grand Moff Tarkin and Darth Vader — Hot Toys', sublabel: 'sixth-scale', href: '/figure/fp_star-wars_hot-toys_hot-toys_action-figures_grand-moff-tarkin-and-darth-vade_5f77da' },
      { type: 'callout', text: 'The spread is not about the character, it is about scale and maker. The same Vader is twenty dollars in 6-inch plastic and several hundred in sixth-scale with cloth and rooted detail. Match the comp to the exact product before you price anything.' },
      { type: 'h2', text: 'What to check before you buy a Vader' },
      { type: 'p', text: 'Pin down three things: scale (3.75-inch, 6-inch, or sixth-scale), maker (Hasbro, Hot Toys, Mafex, and others), and the specific variant. A listing that just says "Darth Vader" means nothing until you know which of the hundred-plus releases it actually is, and the price can swing eighty-fold on that answer alone.' },
      { type: 'p', text: 'Identify the exact one first. [[Look up any Darth Vader figure|/star-wars/character/darth-vader]] for the median and sale count on that release, and [[learn how to read the comps|/guides/how-to-find-action-figure-values]] before you pay.' },
    ],
  },
  {
    slug: 'boba-fett-figure-value',
    title: 'Boba Fett Figures: The Bounty Hunter Premium, Priced Out',
    metaTitle: 'Boba Fett Figure Value — Real Sold Prices, Black Series to Hot Toys | FigurePinner',
    metaDescription:
      'What Boba Fett figures sell for — $20 Black Series up to the $395 Hot Toys throne. Real eBay sold comps and why Fett carries a premium almost no other supporting character matches.',
    dek: 'No character outside the core heroes and Vader gets figured like Fett, or priced like him. The sold data shows the bounty-hunter premium is real.',
    readingMinutes: 5,
    updated: '2026-06-25',
    body: [
      { type: 'p', text: 'Boba Fett is the rare supporting character with main-character demand. He has been figured almost as deeply as Luke or Vader, and unlike most of the supporting cast, his figures carry a real premium at every tier. Dozens of Fett figures have sold comps, running from around nine dollars to nearly four hundred.' },
      { type: 'h2', text: 'The Black Series tier' },
      { type: 'p', text: 'The 6-inch Black Series Fetts mostly sit in the twenties to forties, a touch above the line average, because Fett demand runs hot even on mass-retail product. The exclusives and deluxe versions hold the upper end.' },
      { type: 'comp', fid: 'fp_star-wars_hasbro_black-series_exclusives_boba-fett-and-han-carbonite_f3ab84', label: 'Boba Fett and Han in Carbonite — 6-inch Black Series', sublabel: 'Hasbro exclusive', href: '/figure/fp_star-wars_hasbro_black-series_exclusives_boba-fett-and-han-carbonite_f3ab84' },
      { type: 'h2', text: 'The Hot Toys tier' },
      { type: 'p', text: 'Hot Toys is the ceiling, the same as everywhere in Star Wars. The discontinued sixth-scale Fetts are among the most sought pieces in the line.' },
      { type: 'comp', fid: 'fp_star-wars_hot-toys_hot-toys_action-figures_boba-fett-repaint-armor-throne_529daa', label: 'Boba Fett Repaint Armor & Throne — Hot Toys', sublabel: 'sixth-scale', href: '/figure/fp_star-wars_hot-toys_hot-toys_action-figures_boba-fett-repaint-armor-throne_529daa' },
      { type: 'callout', text: 'Fett’s premium shows up at every tier, not just the top. Even his mass-retail figures run above the line average. That is demand, not scarcity, and demand is the more durable of the two forces.' },
      { type: 'h2', text: 'The vintage legend' },
      { type: 'p', text: 'No Fett guide is complete without the vintage Kenner. The rocket-firing prototype that never shipped is the most famous unreleased figure in the hobby, and it sells for sums that have nothing to do with the rest of this page. The released vintage Fett is common by comparison, but it helped set the keep-it-sealed culture that still drives Star Wars values today.' },
      { type: 'p', text: 'Pricing a specific Fett? [[Look up any Boba Fett figure|/star-wars/character/boba-fett]] for the real median on that release, and [[start from sold comps, not asking prices|/guides/how-to-find-action-figure-values]].' },
    ],
  },
]
